// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proto} from '../models';
import {grpc} from '../models';
import {config} from '../models';

export function DeleteConfig(arg1:string):Promise<void>;

export function ImportProto(arg1:string):Promise<proto.ParseResult>;

export function InvokeMethod(arg1:grpc.InvokeRequest):Promise<grpc.InvokeResponse>;

export function ListConfigs():Promise<Array<config.ConnectionConfig>>;

export function LoadConfig(arg1:string):Promise<config.ConnectionConfig>;

export function LoadMethodScheme(arg1:string,arg2:string):Promise<config.MethodScheme>;

export function LoadProtoPaths():Promise<Array<string>>;

export function OpenFileDialog():Promise<string>;

export function SaveConfig(arg1:string,arg2:config.ConnectionConfig):Promise<void>;

export function SaveMethodScheme(arg1:config.MethodScheme):Promise<void>;

export function SaveProtoPaths(arg1:Array<string>):Promise<void>;
