// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function ImportProto(arg1) {
  return window['go']['main']['App']['ImportProto'](arg1);
}

export function InvokeMethod(arg1) {
  return window['go']['main']['App']['InvokeMethod'](arg1);
}

export function ListConfigs() {
  return window['go']['main']['App']['ListConfigs']();
}

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function LoadMethodScheme(arg1, arg2) {
  return window['go']['main']['App']['LoadMethodScheme'](arg1, arg2);
}

export function LoadProtoPaths() {
  return window['go']['main']['App']['LoadProtoPaths']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SaveMethodScheme(arg1) {
  return window['go']['main']['App']['SaveMethodScheme'](arg1);
}

export function SaveProtoPaths(arg1) {
  return window['go']['main']['App']['SaveProtoPaths'](arg1);
}
